<a href="https://colab.research.google.com/github/gkdivya/ImageProcessing/blob/main/OpenCV/NumpyImageBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [6]:
np.zeros(shape=(2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.ones(shape=(2,2))

array([[1., 1.],
       [1., 1.]])

In [16]:
arr = np.random.randint(0,200, 20)

In [8]:
arr

array([ 83, 196, 125,  16,  35, 157,   4, 151,   9, 116,   8,  27,  18,
       145, 101,  83,  91,  68,  83,  66])

In [22]:
arr.reshape(2,5,2)

array([[[  3,  34],
        [101, 197],
        [ 93,  90],
        [ 61,  59],
        [ 56,  32]],

       [[119,  66],
        [152, 100],
        [168, 124],
        [154,  32],
        [ 20,  88]]])

In [21]:
arr.reshape(5,4)

array([[  3,  34, 101, 197],
       [ 93,  90,  61,  59],
       [ 56,  32, 119,  66],
       [152, 100, 168, 124],
       [154,  32,  20,  88]])

In [17]:
arr.argmax()

3

In [18]:
arr.argmin()

0

In [19]:
arr.max()

197

In [20]:
arr.min()

3

In [29]:
arr = arr.reshape(5,4)
arr[0:3, 0:3]

array([[  3,  34, 101],
       [ 93,  90,  61],
       [ 56,  32, 119]])

In [30]:
arr2 = arr.copy()

In [33]:
arr2[0:2,:]=0
print(arr2)

[[  0   0   0   0]
 [  0   0   0   0]
 [ 56  32 119  66]
 [152 100 168 124]
 [154  32  20  88]]


In [36]:
import matplotlib.pyplot as plt
%matplotlib inline
from PIL import Image

In [37]:
pic = Image.open("https://github.com/gkdivya/ImageProcessing/blob/main/OpenCV/Data/00-puppy.jpg?raw=true")

FileNotFoundError: ignored